// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imposm_internal.proto

#ifndef PROTOBUF_imposm_5finternal_2eproto__INCLUDED
#define PROTOBUF_imposm_5finternal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace imposm {
namespace cache {
namespace internal {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_imposm_5finternal_2eproto();
void protobuf_AssignDesc_imposm_5finternal_2eproto();
void protobuf_ShutdownFile_imposm_5finternal_2eproto();

class DeltaNodes;

// ===================================================================

class DeltaNodes : public ::google::protobuf::Message {
 public:
  DeltaNodes();
  virtual ~DeltaNodes();
  
  DeltaNodes(const DeltaNodes& from);
  
  inline DeltaNodes& operator=(const DeltaNodes& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeltaNodes& default_instance();
  
  void Swap(DeltaNodes* other);
  
  // implements Message ----------------------------------------------
  
  DeltaNodes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeltaNodes& from);
  void MergeFrom(const DeltaNodes& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated sint64 id = 1 [packed = true];
  inline int id_size() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id(int index) const;
  inline void set_id(int index, ::google::protobuf::int64 value);
  inline void add_id(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_id();
  
  // repeated sint32 lat = 2 [packed = true];
  inline int lat_size() const;
  inline void clear_lat();
  static const int kLatFieldNumber = 2;
  inline ::google::protobuf::int32 lat(int index) const;
  inline void set_lat(int index, ::google::protobuf::int32 value);
  inline void add_lat(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      lat() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_lat();
  
  // repeated sint32 lon = 3 [packed = true];
  inline int lon_size() const;
  inline void clear_lon();
  static const int kLonFieldNumber = 3;
  inline ::google::protobuf::int32 lon(int index) const;
  inline void set_lon(int index, ::google::protobuf::int32 value);
  inline void add_lon(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      lon() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_lon();
  
  // @@protoc_insertion_point(class_scope:imposm.cache.internal.DeltaNodes)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > id_;
  mutable int _id_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > lat_;
  mutable int _lat_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > lon_;
  mutable int _lon_cached_byte_size_;
  friend void  protobuf_AddDesc_imposm_5finternal_2eproto();
  friend void protobuf_AssignDesc_imposm_5finternal_2eproto();
  friend void protobuf_ShutdownFile_imposm_5finternal_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static DeltaNodes* default_instance_;
};
// ===================================================================


// ===================================================================

// DeltaNodes

// repeated sint64 id = 1 [packed = true];
inline int DeltaNodes::id_size() const {
  return id_.size();
}
inline void DeltaNodes::clear_id() {
  id_.Clear();
}
inline ::google::protobuf::int64 DeltaNodes::id(int index) const {
  return id_.Get(index);
}
inline void DeltaNodes::set_id(int index, ::google::protobuf::int64 value) {
  id_.Set(index, value);
}
inline void DeltaNodes::add_id(::google::protobuf::int64 value) {
  id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
DeltaNodes::id() const {
  return id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
DeltaNodes::mutable_id() {
  return &id_;
}

// repeated sint32 lat = 2 [packed = true];
inline int DeltaNodes::lat_size() const {
  return lat_.size();
}
inline void DeltaNodes::clear_lat() {
  lat_.Clear();
}
inline ::google::protobuf::int32 DeltaNodes::lat(int index) const {
  return lat_.Get(index);
}
inline void DeltaNodes::set_lat(int index, ::google::protobuf::int32 value) {
  lat_.Set(index, value);
}
inline void DeltaNodes::add_lat(::google::protobuf::int32 value) {
  lat_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DeltaNodes::lat() const {
  return lat_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DeltaNodes::mutable_lat() {
  return &lat_;
}

// repeated sint32 lon = 3 [packed = true];
inline int DeltaNodes::lon_size() const {
  return lon_.size();
}
inline void DeltaNodes::clear_lon() {
  lon_.Clear();
}
inline ::google::protobuf::int32 DeltaNodes::lon(int index) const {
  return lon_.Get(index);
}
inline void DeltaNodes::set_lon(int index, ::google::protobuf::int32 value) {
  lon_.Set(index, value);
}
inline void DeltaNodes::add_lon(::google::protobuf::int32 value) {
  lon_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DeltaNodes::lon() const {
  return lon_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DeltaNodes::mutable_lon() {
  return &lon_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace cache
}  // namespace imposm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_imposm_5finternal_2eproto__INCLUDED
