// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

#ifndef PROTOBUF_internal_2eproto__INCLUDED
#define PROTOBUF_internal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace imposm {
namespace cache {
namespace internal {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_internal_2eproto();
void protobuf_AssignDesc_internal_2eproto();
void protobuf_ShutdownFile_internal_2eproto();

class DeltaCoords;
class DeltaList;

// ===================================================================

class DeltaCoords : public ::google::protobuf::Message {
 public:
  DeltaCoords();
  virtual ~DeltaCoords();
  
  DeltaCoords(const DeltaCoords& from);
  
  inline DeltaCoords& operator=(const DeltaCoords& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeltaCoords& default_instance();
  
  void Swap(DeltaCoords* other);
  
  // implements Message ----------------------------------------------
  
  DeltaCoords* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeltaCoords& from);
  void MergeFrom(const DeltaCoords& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated sint64 ids = 1 [packed = true];
  inline int ids_size() const;
  inline void clear_ids();
  static const int kIdsFieldNumber = 1;
  inline ::google::protobuf::int64 ids(int index) const;
  inline void set_ids(int index, ::google::protobuf::int64 value);
  inline void add_ids(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_ids();
  
  // repeated sint64 lats = 2 [packed = true];
  inline int lats_size() const;
  inline void clear_lats();
  static const int kLatsFieldNumber = 2;
  inline ::google::protobuf::int64 lats(int index) const;
  inline void set_lats(int index, ::google::protobuf::int64 value);
  inline void add_lats(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      lats() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_lats();
  
  // repeated sint64 lons = 3 [packed = true];
  inline int lons_size() const;
  inline void clear_lons();
  static const int kLonsFieldNumber = 3;
  inline ::google::protobuf::int64 lons(int index) const;
  inline void set_lons(int index, ::google::protobuf::int64 value);
  inline void add_lons(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      lons() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_lons();
  
  // @@protoc_insertion_point(class_scope:imposm.cache.internal.DeltaCoords)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > ids_;
  mutable int _ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > lats_;
  mutable int _lats_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > lons_;
  mutable int _lons_cached_byte_size_;
  friend void  protobuf_AddDesc_internal_2eproto();
  friend void protobuf_AssignDesc_internal_2eproto();
  friend void protobuf_ShutdownFile_internal_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static DeltaCoords* default_instance_;
};
// -------------------------------------------------------------------

class DeltaList : public ::google::protobuf::Message {
 public:
  DeltaList();
  virtual ~DeltaList();
  
  DeltaList(const DeltaList& from);
  
  inline DeltaList& operator=(const DeltaList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeltaList& default_instance();
  
  void Swap(DeltaList* other);
  
  // implements Message ----------------------------------------------
  
  DeltaList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeltaList& from);
  void MergeFrom(const DeltaList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated sint64 ids = 1 [packed = true];
  inline int ids_size() const;
  inline void clear_ids();
  static const int kIdsFieldNumber = 1;
  inline ::google::protobuf::int64 ids(int index) const;
  inline void set_ids(int index, ::google::protobuf::int64 value);
  inline void add_ids(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_ids();
  
  // @@protoc_insertion_point(class_scope:imposm.cache.internal.DeltaList)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > ids_;
  mutable int _ids_cached_byte_size_;
  friend void  protobuf_AddDesc_internal_2eproto();
  friend void protobuf_AssignDesc_internal_2eproto();
  friend void protobuf_ShutdownFile_internal_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static DeltaList* default_instance_;
};
// ===================================================================


// ===================================================================

// DeltaCoords

// repeated sint64 ids = 1 [packed = true];
inline int DeltaCoords::ids_size() const {
  return ids_.size();
}
inline void DeltaCoords::clear_ids() {
  ids_.Clear();
}
inline ::google::protobuf::int64 DeltaCoords::ids(int index) const {
  return ids_.Get(index);
}
inline void DeltaCoords::set_ids(int index, ::google::protobuf::int64 value) {
  ids_.Set(index, value);
}
inline void DeltaCoords::add_ids(::google::protobuf::int64 value) {
  ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
DeltaCoords::ids() const {
  return ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
DeltaCoords::mutable_ids() {
  return &ids_;
}

// repeated sint64 lats = 2 [packed = true];
inline int DeltaCoords::lats_size() const {
  return lats_.size();
}
inline void DeltaCoords::clear_lats() {
  lats_.Clear();
}
inline ::google::protobuf::int64 DeltaCoords::lats(int index) const {
  return lats_.Get(index);
}
inline void DeltaCoords::set_lats(int index, ::google::protobuf::int64 value) {
  lats_.Set(index, value);
}
inline void DeltaCoords::add_lats(::google::protobuf::int64 value) {
  lats_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
DeltaCoords::lats() const {
  return lats_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
DeltaCoords::mutable_lats() {
  return &lats_;
}

// repeated sint64 lons = 3 [packed = true];
inline int DeltaCoords::lons_size() const {
  return lons_.size();
}
inline void DeltaCoords::clear_lons() {
  lons_.Clear();
}
inline ::google::protobuf::int64 DeltaCoords::lons(int index) const {
  return lons_.Get(index);
}
inline void DeltaCoords::set_lons(int index, ::google::protobuf::int64 value) {
  lons_.Set(index, value);
}
inline void DeltaCoords::add_lons(::google::protobuf::int64 value) {
  lons_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
DeltaCoords::lons() const {
  return lons_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
DeltaCoords::mutable_lons() {
  return &lons_;
}

// -------------------------------------------------------------------

// DeltaList

// repeated sint64 ids = 1 [packed = true];
inline int DeltaList::ids_size() const {
  return ids_.size();
}
inline void DeltaList::clear_ids() {
  ids_.Clear();
}
inline ::google::protobuf::int64 DeltaList::ids(int index) const {
  return ids_.Get(index);
}
inline void DeltaList::set_ids(int index, ::google::protobuf::int64 value) {
  ids_.Set(index, value);
}
inline void DeltaList::add_ids(::google::protobuf::int64 value) {
  ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
DeltaList::ids() const {
  return ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
DeltaList::mutable_ids() {
  return &ids_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace cache
}  // namespace imposm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_internal_2eproto__INCLUDED
